Internal Server Error: /api/client-login/
Traceback (most recent call last):
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\rest_framework\views.py", line 167, in http_method_not_allowed
    raise exceptions.MethodNotAllowed(request.method)
rest_framework.exceptions.MethodNotAllowed: Method "GET" not allowed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\django\utils\module_loading.py", line 16, in cached_import
    return getattr(module, class_name)
AttributeError: module 'registration.views' has no attribute 'custom_exception_handler'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\rest_framework\settings.py", line 177, in import_from_string
    return import_string(val)
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\django\utils\module_loading.py", line 32, in import_string
    raise ImportError(
ImportError: Module "registration.views" does not define a "custom_exception_handler" attribute/class

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\rest_framework\views.py", line 463, in handle_exception
    exception_handler = self.get_exception_handler()
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\rest_framework\views.py", line 298, in get_exception_handler
    return self.settings.EXCEPTION_HANDLER
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\rest_framework\settings.py", line 225, in __getattr__
    val = perform_import(val, attr)
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\rest_framework\settings.py", line 166, in perform_import
    return import_from_string(val, setting_name)
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\rest_framework\settings.py", line 180, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'registration.views.custom_exception_handler' for API setting 'EXCEPTION_HANDLER'. ImportError: Module "registration.views" does not define a "custom_exception_handler" attribute/class.
"GET /api/client-login/ HTTP/1.1" 500 145
Internal Server Error: /api/client-login/
Traceback (most recent call last):
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\rest_framework\views.py", line 167, in http_method_not_allowed
    raise exceptions.MethodNotAllowed(request.method)
rest_framework.exceptions.MethodNotAllowed: Method "GET" not allowed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\django\utils\module_loading.py", line 16, in cached_import
    return getattr(module, class_name)
AttributeError: module 'registration.views' has no attribute 'custom_exception_handler'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\rest_framework\settings.py", line 177, in import_from_string
    return import_string(val)
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\django\utils\module_loading.py", line 32, in import_string
    raise ImportError(
ImportError: Module "registration.views" does not define a "custom_exception_handler" attribute/class

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\rest_framework\views.py", line 463, in handle_exception
    exception_handler = self.get_exception_handler()
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\rest_framework\views.py", line 298, in get_exception_handler
    return self.settings.EXCEPTION_HANDLER
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\rest_framework\settings.py", line 225, in __getattr__
    val = perform_import(val, attr)
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\rest_framework\settings.py", line 166, in perform_import
    return import_from_string(val, setting_name)
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\rest_framework\settings.py", line 180, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'registration.views.custom_exception_handler' for API setting 'EXCEPTION_HANDLER'. ImportError: Module "registration.views" does not define a "custom_exception_handler" attribute/class.
"GET /api/client-login/ HTTP/1.1" 500 145
Internal Server Error: /api/client-login/
Traceback (most recent call last):
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\rest_framework\views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\rest_framework\views.py", line 167, in http_method_not_allowed
    raise exceptions.MethodNotAllowed(request.method)
rest_framework.exceptions.MethodNotAllowed: Method "GET" not allowed.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\django\utils\module_loading.py", line 30, in import_string
    return cached_import(module_path, class_name)
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\django\utils\module_loading.py", line 16, in cached_import
    return getattr(module, class_name)
AttributeError: module 'registration.views' has no attribute 'custom_exception_handler'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\rest_framework\settings.py", line 177, in import_from_string
    return import_string(val)
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\django\utils\module_loading.py", line 32, in import_string
    raise ImportError(
ImportError: Module "registration.views" does not define a "custom_exception_handler" attribute/class

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\django\core\handlers\exception.py", line 55, in inner
    response = get_response(request)
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\django\core\handlers\base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\django\views\decorators\csrf.py", line 56, in wrapper_view
    return view_func(*args, **kwargs)
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\django\views\generic\base.py", line 104, in view
    return self.dispatch(request, *args, **kwargs)
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\rest_framework\views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\rest_framework\views.py", line 463, in handle_exception
    exception_handler = self.get_exception_handler()
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\rest_framework\views.py", line 298, in get_exception_handler
    return self.settings.EXCEPTION_HANDLER
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\rest_framework\settings.py", line 225, in __getattr__
    val = perform_import(val, attr)
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\rest_framework\settings.py", line 166, in perform_import
    return import_from_string(val, setting_name)
  File "C:\Users\Sylvester\Envs\space\lib\site-packages\rest_framework\settings.py", line 180, in import_from_string
    raise ImportError(msg)
ImportError: Could not import 'registration.views.custom_exception_handler' for API setting 'EXCEPTION_HANDLER'. ImportError: Module "registration.views" does not define a "custom_exception_handler" attribute/class.
"GET /api/client-login/ HTTP/1.1" 500 145
